name = "rasta-rock"
compatibility_date = "2023-10-30"
send_metrics = false
node_compat = true
#route = "app.t4stack.com/*"
#workers_dev = false
account_id = "8b065ed43bf24ab7770ea3ae7e98e0a8"

[[ d1_databases ]]
binding = "DB"
database_name = "PREV_RASTAROCK"
database_id = "060bf3b7-2117-483b-9621-93a4b775e1fa"
#workers_dev = true
